"""Initial schema: prospect/audit/contact/outreach + user/subscription/byok + funnel.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-17

Hand-written rather than autogenerated so we control:
  - the order of dependent FKs / enums,
  - `CREATE EXTENSION citext` (required for CITEXT columns),
  - composite-column indexes Alembic wouldn't infer.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


# create_type=False because we run .create()/.drop() explicitly in
# upgrade()/downgrade(); without this flag SQLAlchemy would re-emit
# `CREATE TYPE` again when it sees the type used on a column.
_E = dict(create_type=False)

PROSPECT_STATUS = postgresql.ENUM(
    "queued", "audited", "failed", "skipped", name="prospect_status", **_E
)
USER_PLAN = postgresql.ENUM("free", "pro_usd", "pro_inr", name="user_plan", **_E)
PROCESSOR = postgresql.ENUM("stripe", "razorpay", name="processor", **_E)
SUBSCRIPTION_STATUS = postgresql.ENUM(
    "active", "past_due", "canceled", "halted", name="subscription_status", **_E
)
BYOK_PROVIDER = postgresql.ENUM("openai", "gemini", name="byok_provider", **_E)
FUNNEL_STAGE = postgresql.ENUM(
    "discovered", "visited", "audited", "scanned", "contacted",
    "engaged", "paywalled", "trialing", "converted", "retained",
    "at_risk", "churned",
    name="funnel_stage", **_E,
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # gen_random_uuid()

    bind = op.get_bind()
    PROSPECT_STATUS.create(bind, checkfirst=True)
    USER_PLAN.create(bind, checkfirst=True)
    PROCESSOR.create(bind, checkfirst=True)
    SUBSCRIPTION_STATUS.create(bind, checkfirst=True)
    BYOK_PROVIDER.create(bind, checkfirst=True)
    FUNNEL_STAGE.create(bind, checkfirst=True)

    op.create_table(
        "seed_keyword",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("keyword", sa.String(256), nullable=False),
        sa.Column("vertical", sa.String(64)),
        sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("keyword", name="uq_seed_keyword_keyword"),
    )

    op.create_table(
        "prospect",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("url", sa.Text, nullable=False),
        sa.Column("domain", sa.String(255), nullable=False),
        sa.Column("target_keyword", sa.String(256), nullable=False),
        sa.Column("source", sa.String(32), nullable=False, server_default="serpapi"),
        sa.Column("status", PROSPECT_STATUS, nullable=False, server_default="queued"),
        sa.Column("failure_reason", sa.Text),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("url", name="uq_prospect_url"),
    )
    op.create_index("ix_prospect_domain", "prospect", ["domain"])
    op.create_index("ix_prospect_target_keyword", "prospect", ["target_keyword"])
    op.create_index("ix_prospect_status", "prospect", ["status"])

    op.create_table(
        "audit",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("prospect_id", sa.BigInteger,
                  sa.ForeignKey("prospect.id", ondelete="CASCADE"), nullable=False),
        sa.Column("aeo_score", sa.SmallInteger, nullable=False),
        sa.Column("band", sa.String(32), nullable=False),
        sa.Column("fanout_payload", postgresql.JSONB),
        sa.Column("missing_gap_types", postgresql.JSONB),
        sa.Column("failed_checks", postgresql.JSONB),
        sa.Column("report_path", sa.Text),
        sa.Column("token_jti", postgresql.UUID(as_uuid=True), nullable=False,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("token_jti", name="uq_audit_token_jti"),
    )
    op.create_index("ix_audit_prospect_id", "audit", ["prospect_id"])

    op.create_table(
        "contact",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("prospect_id", sa.BigInteger,
                  sa.ForeignKey("prospect.id", ondelete="CASCADE"), nullable=False),
        sa.Column("email", postgresql.CITEXT, nullable=False),
        sa.Column("name", sa.String(128)),
        sa.Column("role", sa.String(128)),
        sa.Column("source", sa.String(64)),
        sa.Column("verified", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("prospect_id", "email", name="uq_contact_prospect_email"),
    )
    op.create_index("ix_contact_prospect_id", "contact", ["prospect_id"])

    op.create_table(
        "outreach",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("contact_id", sa.BigInteger,
                  sa.ForeignKey("contact.id", ondelete="CASCADE"), nullable=False),
        sa.Column("audit_id", sa.BigInteger,
                  sa.ForeignKey("audit.id", ondelete="CASCADE"), nullable=False),
        sa.Column("template_variant", sa.String(64), nullable=False,
                  server_default="cold_outreach"),
        sa.Column("subject", sa.String(512)),
        sa.Column("body_hash", sa.String(64)),
        sa.Column("sent_at", sa.DateTime(timezone=True)),
        sa.Column("opens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("clicks", sa.Integer, nullable=False, server_default="0"),
        sa.Column("replied", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("error", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("contact_id", "audit_id", "template_variant",
                            name="uq_outreach_contact_audit_variant"),
    )
    op.create_index("ix_outreach_contact_id", "outreach", ["contact_id"])
    op.create_index("ix_outreach_audit_id", "outreach", ["audit_id"])

    op.create_table(
        "user_",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("session_id", sa.String(64), nullable=False),
        sa.Column("email", postgresql.CITEXT),
        sa.Column("ip_country", sa.String(2)),
        sa.Column("plan", USER_PLAN, nullable=False, server_default="free"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("session_id", name="uq_user_session_id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )

    op.create_table(
        "scan",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("ip", postgresql.INET, nullable=False),
        sa.Column("user_session_id", sa.String(64)),
        sa.Column("path", sa.String(128), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )
    # Supports the hot-path "how many scans from this IP today?" query.
    op.create_index("ix_scan_ip_scanned_at", "scan", ["ip", "scanned_at"])

    op.create_table(
        "subscription",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("user_.id", ondelete="CASCADE"), nullable=False),
        sa.Column("processor", PROCESSOR, nullable=False),
        sa.Column("external_id", sa.String(128), nullable=False),
        sa.Column("status", SUBSCRIPTION_STATUS, nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("external_id", name="uq_subscription_external_id"),
    )
    op.create_index("ix_subscription_user_id", "subscription", ["user_id"])

    op.create_table(
        "byok_validation",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("user_.id", ondelete="CASCADE"), nullable=False),
        sa.Column("key_hash", sa.String(64), nullable=False),
        sa.Column("provider", BYOK_PROVIDER, nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("valid", sa.Boolean, nullable=False),
        sa.UniqueConstraint("user_id", "key_hash", name="uq_byok_user_keyhash"),
    )
    op.create_index("ix_byok_user_id", "byok_validation", ["user_id"])

    op.create_table(
        "webhook_event",
        sa.Column("id", sa.String(128), primary_key=True),
        sa.Column("processor", PROCESSOR, nullable=False),
        sa.Column("event_type", sa.String(128), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("processed_at", sa.DateTime(timezone=True)),
        sa.Column("error", sa.Text),
    )

    op.create_table(
        "funnel_event",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("user_.id", ondelete="SET NULL")),
        sa.Column("prospect_id", sa.BigInteger,
                  sa.ForeignKey("prospect.id", ondelete="SET NULL")),
        sa.Column("audit_id", sa.BigInteger,
                  sa.ForeignKey("audit.id", ondelete="SET NULL")),
        sa.Column("contact_id", sa.BigInteger,
                  sa.ForeignKey("contact.id", ondelete="SET NULL")),
        sa.Column("stage", FUNNEL_STAGE, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("metadata", postgresql.JSONB),
    )
    op.create_index("ix_funnel_event_stage", "funnel_event", ["stage"])
    op.create_index("ix_funnel_event_occurred_at", "funnel_event", ["occurred_at"])
    op.create_index("ix_funnel_event_stage_occurred",
                    "funnel_event", ["stage", "occurred_at"])
    op.create_index("ix_funnel_event_user_id", "funnel_event", ["user_id"])
    op.create_index("ix_funnel_event_prospect_id", "funnel_event", ["prospect_id"])


def downgrade() -> None:
    op.drop_table("funnel_event")
    op.drop_table("webhook_event")
    op.drop_table("byok_validation")
    op.drop_table("subscription")
    op.drop_table("scan")
    op.drop_table("user_")
    op.drop_table("outreach")
    op.drop_table("contact")
    op.drop_table("audit")
    op.drop_table("prospect")
    op.drop_table("seed_keyword")

    bind = op.get_bind()
    FUNNEL_STAGE.drop(bind, checkfirst=True)
    BYOK_PROVIDER.drop(bind, checkfirst=True)
    SUBSCRIPTION_STATUS.drop(bind, checkfirst=True)
    PROCESSOR.drop(bind, checkfirst=True)
    USER_PLAN.drop(bind, checkfirst=True)
    PROSPECT_STATUS.drop(bind, checkfirst=True)
